/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.absanr.factutrack.view;
import com.absanr.factutrack.view.DashboardFrame;
import io.github.cdimascio.dotenv.Dotenv;
import javax.swing.JOptionPane;


/**
 *
 * @author Devpr
 */
public class LoginFrame extends javax.swing.JFrame {
    
    // Carga de variables de entorno
    private static final Dotenv dotenv = Dotenv.load();
    private static final String ADMIN_USERNAME = dotenv.get("ADMIN_USERNAME");
    private static final String ADMIN_PASSWORD = dotenv.get("ADMIN_PASSWORD");

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        errorMessage_jTextField1.setEditable(false); // Evita que el mensaje de error sea editable
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jUsernameField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        login_jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        errorMessage_jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jUsernameField1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jUsernameField1.setBorder(null);
        jUsernameField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jUsernameField1FocusGained(evt);
            }
        });
        jUsernameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsernameField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jUsernameField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 250, 40));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 250, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("Contraseña");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 250, -1));

        jPasswordField1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPasswordField1.setBorder(null);
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 260, 40));

        login_jButton1.setBackground(new java.awt.Color(51, 153, 255));
        login_jButton1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        login_jButton1.setForeground(new java.awt.Color(255, 255, 255));
        login_jButton1.setText("Iniciar Sesión");
        login_jButton1.setBorder(null);
        login_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(login_jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 260, 40));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("Login - FactuTrack");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 210, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 260, 20));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 260, 10));

        errorMessage_jTextField1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        errorMessage_jTextField1.setForeground(new java.awt.Color(255, 51, 51));
        errorMessage_jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        errorMessage_jTextField1.setBorder(null);
        errorMessage_jTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
        errorMessage_jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        errorMessage_jTextField1.setDisabledTextColor(new java.awt.Color(255, 204, 204));
        errorMessage_jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorMessage_jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(errorMessage_jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 260, 50));

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 450));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 280, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Métodos públicos para acceder a los componentes desde el controlador
    // Métodos accesores para el controlador
    public javax.swing.JButton getLoginButton() {
        return login_jButton1;
    }

    public javax.swing.JTextField getUsernameField() {
        return jUsernameField1;
    }

    public javax.swing.JPasswordField getPasswordField() {
        return jPasswordField1;
    }

    public void setErrorMessage(String message) {
        errorMessage_jTextField1.setText(message);
    }

    public void clearErrorMessage() {
        errorMessage_jTextField1.setText("");
    }

    
    private void jUsernameField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUsernameField1FocusGained
        // Limpiar el mensaje de error si lo hubiera
        errorMessage_jTextField1.setText("");
    }//GEN-LAST:event_jUsernameField1FocusGained

    private void jUsernameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsernameField1ActionPerformed
        // Pasar el foco al campo de contraseña
        jPasswordField1.requestFocus();
    }//GEN-LAST:event_jUsernameField1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // Simular clic en el botón de login
        login_jButton1.doClick();
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void login_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_jButton1ActionPerformed
        // Obtener los valores de los campos
        String username = jUsernameField1.getText();
        String password = new String(jPasswordField1.getPassword());

        // Verificar credenciales (puedes delegar esto a un controlador)
        if (ADMIN_USERNAME.equals(username) && ADMIN_PASSWORD.equals(password)) {
            // Mostrar el Dashboard y cerrar el Login
            JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso.");
            this.dispose(); // Cerrar ventana actual
            new DashboardFrame().setVisible(true); // Abrir Dashboard
        } else {
            // Mostrar mensaje de error
            errorMessage_jTextField1.setText("Usuario o contraseña incorrectos.");
        }
    }//GEN-LAST:event_login_jButton1ActionPerformed

    private void errorMessage_jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorMessage_jTextField1ActionPerformed
        // No hacer nada porque no debería ser interactivo
        // Idealmente, asegurarte de que está deshabilitado:
        errorMessage_jTextField1.setEditable(false);    
    }//GEN-LAST:event_errorMessage_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JTextField errorMessage_jTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jUsernameField1;
    private javax.swing.JButton login_jButton1;
    // End of variables declaration//GEN-END:variables
}
